### ISSUE TITLE
Unknown directive?

### ISSUE THREAD

**Issue by FTwOoO** [caddyserver/caddydev#11]
I follow the commands to generate an example:

```
$ go get github.com/caddyserver/caddydev
$ mkdir hello
$ cd hello
$ caddydev new
$ caddydev
```

 it complains " Parse error: Unknown directive 'hello' ", but if i insert "hello" directive into caddyhttp/httpserver/plugins.go:

```
var directives = []string{
	"hello",
```

things done.

so, why not make `caddydev` to add new directive automatically when building plugin?
 or just remove hardcoding directives of http server type, and add new directive dynamically in `RegisterPlugin` function?

**Comment by abiosoft** [comment]
It was doing that before now. I removed it in this commit https://github.com/caddyserver/caddydev/commit/0f265138766f18d5c5a216e641f308961befc73b due to some concerns raised by @mholt.

**Comment by abiosoft** [comment]
How about an `CADDY_DEV_MODE` environment variable that you can check.
So you can have something like this in your plugin
```go
func init(){
    if os.Getenv("CADDY_DEV_MODE") == "1" {
        httpserver.RegisterDevDirective("hello", "")
    }
}
```

**Comment by abiosoft** [comment]
Update caddydev and that snippet above works.

`caddydev new` has been updated to include that snippet as well.

That's as far as I can go for now considering a new build and dev tool is in the works.

**Comment by FTwOoO** [comment]
Thans, that's good
