### ISSUE TITLE
write something about paths in the documentation

### ISSUE THREAD

**Issue by wmark** [caddyserver/caddydev#2]
I am following the (scattered) documentations on how to write a module for *Caddy*…:

```bash
export GOPATH=$(mktemp -d -t "caddydev.XXXXXX")

go get -v -t github.com/caddyserver/caddydev
go get -v -t -u github.com/mholt/caddy
go get -v -t -d blitznote.com/src/caddy.upload

eval cd $GOPATH/src/blitznote.com/src/caddy.upload
```

… and am getting this error:
```bash
$ eval $GOPATH/bin/caddydev --source blitznote.com/src/caddy.upload upload
Invalid source directory.
```

Alright, we obviously need an absolute path, so:
```bash
$ eval $GOPATH/bin/caddydev --source $GOPATH/src/blitznote.com/src/caddy.upload upload &
$ curl -f 127.0.0.1:2015
curl: (22) The requested URL returned error: 404 Not Found
$ kill %1
```

Directive ```caddy.upload``` doesn't work, too. At this point the only file, ```holla.go```, is a copy of the example ```hello.go```.

In case of the second error I expect *caddydev* to not start at all and throw an error like "directive without effect" or "directive not implemented."

**Comment by wmark** [comment]
I've discovered that I need a ```Caddyfile``` like this, despite having passed the directive to *caddydev*:
```text
0.0.0.0

upload
```

**Comment by mholt** [comment]
That's correct; we'll clarify the docs. The Caddyfile is still required (unless you want to use default settings) and you still need to specify your directive there because you may also want to test it with some extra params. Think of caddydev as a convenient replacement for `go run ...` where all it does is splice in your directive, making it available to your Caddyfile.

**Comment by wmark** [comment]
*caddydev*'s README doesn't reflect the new changes. I've followed it with these results:

```bash
$ eval $GOPATH/bin/caddydev --source src/blitznote.com/src/caddy.upload upload
Invalid source directory.

$ eval $GOPATH/bin/caddydev --source $GOPATH/src/blitznote.com/src/caddy.upload upload
cannot place 'upload' after '': directive '' not found
```

**Comment by mholt** [comment]
Are you referring to this wording being confusing?

```
  -s, --source="."   Source code directory or go get path.
```

**Comment by wmark** [comment]
It's just the out-of-the-box experience that needs fixing for other devs.

- README still does not contain absolute paths.
- *caddydev* or *caddy* don't work with (the default) empty directive ```-a``` anymore. 
   ```caddydev … -a browse upload &``` will work, though.

I suggest some sort of integration test for *caddydev* (semaphore.io? wercker?) which issues a notification as soon as the example from the documentations and/or README result in errors.
