### ISSUE TITLE
caddy API changed

### ISSUE THREAD

**Issue by LrsK** [caddyserver/caddydev#4]
It seems that https://github.com/mholt/caddy has changed its API a bit, and so caddydev needs to be altered to work.

directivesFile = "config/directives.go" in build.go needs to be:
directivesFile = "caddy/directives.go" 

at least that is what I did to make it work

**Comment by abiosoft** [comment]
Thanks a lot for this.

I'll update it asap.

**Comment by mholt** [comment]
Oh yeah. I was gonna tell you about that. :sweat_smile:

**Comment by mholt** [comment]
Thanks @abiosoft !
