### ISSUE TITLE
caddydev not support directory name with dash in it

### ISSUE THREAD

**Issue by meepeek** [caddyserver/caddydev#8]
To reproduce the problem:
```
mkdir caddy-dev
cd caddy-dev
caddydev new
caddydev
```

**Comment by abiosoft** [comment]
The directory name becomes the package name of the generated source, and the directory name is expected to become the directive to use in the Caddyfile.

1. Go does not support hyphen `-` in package names. I would advise you go with underscore `_` instead or edit the generated `caddy-dev.go` file and change the package name.
2. That does not follow Caddyfile convention, directives derived from multiple words have them written together. e.g. `realip`, `basicauth`.

Thanks.

**Comment by meepeek** [comment]
If that so, I think there should be a warning or error report as the user type 'caddydev new', or else it should not use the directory name to begin with. It does not make sense that the tool automatically generate the code for a user and then find out later that there was an error in the code generated.

**Comment by abiosoft** [comment]
You have a point there and I am actually considering the same. A warning it is.
